### PR TITLE
Jump

### PR DESCRIPTION
**Pull request by sbelak**
Added jump and until to ogre.branch

Potential issues:
* f-to-jump-predicate is potentially too smart. Is it correct we change the arity of predicate fn based on Traverser type (SimpleTraverser vs. PathTraverser)? If not, should we drop path argument altogether, or should it be nil for SimpleTraverser?

### CODE REVIEW

**Comment by spmallette** [comment]
Note that there is some discussion in TinkerPop right now about whether `jump` will need to exist at all as we are seeing how other steps can accomplish what it is doing thus making it obsolete.  

Note the "looping constructs" conversation here if interested:  https://github.com/tinkerpop/tinkerpop3/issues/411

Regarding `f-to-jump-predicate`, I don't think you need to distinguish the two.  Both `SimpleTraverser` and `PathTraverser` return a `Path`.  They just have different methods of calculating that `Path`  Does that make sense?

**Comment by sbelak** [comment]
I suppose I should start following TP3 development. Thanks for the heads up.

Apropos f-to-jump-predicate, that was my thinking too, but turns out if we don't differentiate, it explodes: 

```
1. Caused by java.lang.IllegalStateException
   Path tracking is not supported by this Traverser: class
   com.tinkerpop.gremlin.process.traversers.SimpleTraverser

          SimpleTraverser.java:   58  com.tinkerpop.gremlin.process.traversers.SimpleTraverser/path
                      util.clj:   92  clojurewerkz.ogre.util/f-to-jump-predicate/fn
                      util.clj:   85  clojurewerkz.ogre.util/f-to-predicate/reify
                 JumpStep.java:  137  com.tinkerpop.gremlin.process.graph.step.branch.JumpStep/doJump
                 JumpStep.java:   68  com.tinkerpop.gremlin.process.graph.step.branch.JumpStep/standardAlgorithm
                 JumpStep.java:   55  com.tinkerpop.gremlin.process.graph.step.branch.JumpStep/processNextStart
             AbstractStep.java:  105  com.tinkerpop.gremlin.process.util.AbstractStep/hasNext
   ExpandableStepIterator.java:   33  com.tinkerpop.gremlin.process.util.ExpandableStepIterator/next
              FlatMapStep.java:   38  com.tinkerpop.gremlin.process.graph.step.map.FlatMapStep/processNextStart
             AbstractStep.java:   89  com.tinkerpop.gremlin.process.util.AbstractStep/next
             AbstractStep.java:   15  com.tinkerpop.gremlin.process.util.AbstractStep/next
                Traversal.java:  181  com.tinkerpop.gremlin.process.Traversal/fill
                Traversal.java:  157  com.tinkerpop.gremlin.process.Traversal/toList
                 traversal.clj:   27  clojurewerkz.ogre.traversal/into-vec!
               branch_test.clj:   11  clojurewerkz.ogre.branch-test/eval7586
```

**Comment by spmallette** [comment]
hmmm - fair enough.  i guess there is something i don't complete understand about `SimpleTraverser` still.  i'll inquire/research further....in the mean time, let's assume your approach is right and that we "change the arity of predicate fn" based on the type of `Traverser`.  is that ok with you?

**Comment by sbelak** [comment]
Seems it became supported sometime after M6, so it's probably best to wait.

**Comment by michaelklishin** [comment]
Just a note: I've seen the suggestion to wait but this also no longer can be merged cleanly.

**Comment by sbelak** [comment]
I'll update the patch as soon as a decision is made how to proceed (and we target M7 so we don't have to differentiate Traversers).

**Comment by spmallette** [comment]
The `jump()` step never made it to TinkerPop 3.x GA. I've restructured all of Ogre to work with the latest version of TinkerPop at 3.2.0-incubating. Please see the latest changes on the master branch and note that a milestone release is currently being planned for release very soon

**Pull request closed without merging**
