### PR TITLE
Bugfix: use a set for into-set!

### PR DESCRIPTION
**Pull request by Harleqin**

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for submitting this fix.

**Comment by Harleqin** [comment]
Thanks for the quick merge, but I am a bit concerned by the failing build.  It seems that there is a big test suite that doesn't actually test anything (except that it somehow compiles).  What are the plans for that?

**Comment by spmallette** [comment]
I just noticed the failing build and tried to push something to fix it. It builds ok for me locally with a simple `lein test`.

**Comment by spmallette** [comment]
That was fast - it's green now

**Pull request merged**
